Repository codesquad-members-2023-team2/issue-tracker, pull requests merged in 2023-05, with the labels that each got.

#13 chore #3: 초기 개발 환경 설정
  fe/.eslintrc.json
  fe/.gitignore
  fe/.prettierrc
  fe/.storybook/main.ts
  fe/.storybook/preview.ts
  fe/README.md
  fe/package-lock.json
  fe/package.json
  fe/public/favicon.ico
  fe/public/index.html
  fe/public/logo192.png
  fe/public/logo512.png
  fe/public/manifest.json
  fe/public/robots.txt
  fe/src/App.css
  fe/src/App.test.tsx
  fe/src/App.tsx
  fe/src/index.css
  fe/src/index.tsx
  fe/src/logo.svg
  fe/src/react-app-env.d.ts
  fe/src/reportWebVitals.ts
  fe/src/setupTests.ts
  fe/src/stories/Button.stories.ts
  fe/src/stories/Button.tsx
  fe/src/stories/Header.stories.ts
  fe/src/stories/Header.tsx
  fe/src/stories/Introduction.mdx
  fe/src/stories/Page.stories.ts
  fe/src/stories/Page.tsx
  fe/src/stories/assets/code-brackets.svg
  fe/src/stories/assets/colors.svg
  fe/src/stories/assets/comments.svg
  fe/src/stories/assets/direction.svg
  fe/src/stories/assets/flow.svg
  fe/src/stories/assets/plugin.svg
  fe/src/stories/assets/repo.svg
  fe/src/stories/assets/stackalt.svg
  fe/src/stories/button.css
  fe/src/stories/header.css
  fe/src/stories/page.css
  fe/tailwind.config.js
  fe/tsconfig.json
Labels: 🧑🏻‍💻 FE

#22 feat #4: header 컴포넌트 구현
  fe/public/assets/Logo.svg
  fe/src/App.css
  fe/src/App.tsx
  fe/src/Header/Header.stories.ts
  fe/src/Header/Header.tsx
  fe/src/common/Logo/Logo.stories.ts
  fe/src/common/Logo/Logo.tsx
  fe/src/common/Profile/Profile.stories.ts
  fe/src/common/Profile/Profile.tsx
  fe/src/index.css
  fe/src/stories/Button.stories.ts
  fe/src/stories/Header.stories.ts
  fe/src/stories/Header.tsx
  fe/src/stories/Page.stories.ts
  fe/src/stories/Page.tsx
  fe/src/stories/header.css
  fe/src/stories/page.css
  fe/tailwind.config.js
Labels: 🧑🏻‍💻 FE, 🚀 Feat, 🎨 UI

#25 feat #4: 메인 이슈 리스트 구현
  fe/components/IssueList/Issue.stories.tsx
  fe/components/IssueList/Issue.tsx
  fe/components/IssueList/IssueList.stories.tsx
  fe/components/IssueList/IssueList.tsx
Labels: 🧑🏻‍💻 FE, 🚀 Feat, 🎨 UI

#27 feat #4: 레이블 컴포넌트 구현
  fe/src/common/Label/Label.stories.ts
  fe/src/common/Label/Label.tsx
Labels: 🧑🏻‍💻 FE, 🚀 Feat, 🎨 UI

#30 feat #4: 절대 경로 설정 및 이슈 테스트 케이스 추가
  fe/src/App.tsx
  fe/src/common/Label/Label.stories.ts
  fe/src/common/Label/Label.tsx
  fe/src/common/Label/index.tsx
  fe/src/common/Logo/Logo.tsx
  fe/src/common/Logo/index.tsx
  fe/src/common/Profile/Profile.stories.ts
  fe/src/common/Profile/index.tsx
  fe/src/components/FilterBar/FilterBar.stories.ts
  fe/src/components/FilterBar/FilterBar.tsx
  fe/src/components/Header/Header.tsx
  fe/src/components/IssueList/Issue.stories.ts
  fe/src/components/IssueList/Issue.tsx
  fe/src/components/IssueList/IssueList.stories.ts
  fe/src/components/IssueList/IssueList.tsx
  fe/src/components/NavLinks/NavLinks.stories.ts
  fe/tailwind.config.js
Labels: 🧑🏻‍💻 FE, 🚀 Feat, 🎨 UI

#34 feat #14: /api/에서 Home에 필요한 Dto 구현 및 단일 객체 테스트
  be/src/main/java/com/issuetracker/controller/IssueListController.java
  be/src/main/java/com/issuetracker/controller/TestController.java
  be/src/main/java/com/issuetracker/dto/FilterLabelDto.java
  be/src/main/java/com/issuetracker/dto/FilterMilestoneDto.java
  be/src/main/java/com/issuetracker/dto/FilterUserDto.java
  be/src/main/java/com/issuetracker/dto/IssueDto.java
  be/src/main/java/com/issuetracker/dto/IssueLabelDto.java
  be/src/main/java/com/issuetracker/dto/IssueListDto.java
  be/src/main/java/com/issuetracker/dto/TestDto.java
Labels: 🧑🏻‍💻 BE, 🚀 Feat

#31 style #4: theme-setting
  fe/package-lock.json
  fe/package.json
  fe/src/common/Label/Label.tsx
  fe/src/components/FilterBar/FilterBar.tsx
  fe/src/components/Header/Header.tsx
  fe/src/components/IssueList/Issue.tsx
  fe/src/components/IssueList/IssueList.tsx
  fe/src/components/NavLinks/NavLinks.tsx
  fe/src/index.css
  fe/tailwind.config.js
Labels: 🧑🏻‍💻 FE, 🎨 UI

#33 feat #4: button 컴포넌트 구현 및 기타 설정
  fe/.storybook/main.ts
  fe/package-lock.json
  fe/package.json
  fe/public/index.html
  fe/src/assets/chevronDown.svg
  fe/src/assets/closedIssue.svg
  fe/src/assets/dropDownArrow.svg
  fe/src/assets/label.svg
  fe/src/assets/logo.svg
  fe/src/assets/milestone.svg
  fe/src/assets/openedIssue.svg
  fe/src/assets/plus.svg
  fe/src/assets/search.svg
  fe/src/common/Button/Button.stories.ts
  fe/src/common/Button/index.tsx
  fe/src/common/Label/Label.stories.ts
  fe/src/common/Label/Label.tsx
  fe/src/common/Label/index.tsx
  fe/src/common/Logo/Logo.stories.ts
  fe/src/common/Logo/Logo.tsx
  fe/src/common/Logo/index.tsx
  fe/src/common/Profile/Profile.stories.ts
  fe/src/common/Profile/Profile.tsx
  fe/src/common/Profile/index.tsx
  fe/src/components/FilterBar/FilterBar.tsx
  fe/src/components/Header/Header.tsx
  fe/src/components/IssueList/Issue.tsx
  fe/src/components/NavLinks/NavLinks.tsx
  fe/src/index.css
  fe/src/index.tsx
  fe/tailwind.config.js
  fe/tsconfig.json
Labels: 🧑🏻‍💻 FE, 🚀 Feat, 🛠 Fix, 🎨 UI

#38 refactor #4: assets 경로 수정, 기본 폰트 및 색상 설정
  fe/.storybook/preview-body.html
  fe/src/common/FilterItem/FilterItem.stories.ts
  fe/src/common/FilterItem/FilterItem.tsx
  fe/src/common/Logo/Logo.stories.ts
  fe/src/common/Logo/index.tsx
  fe/src/common/Profile/index.tsx
  fe/src/components/FilterBar/FilterBar.tsx
  fe/src/components/Header/Header.tsx
  fe/src/components/IssueList/Issue.tsx
  fe/src/components/IssueList/IssueList.tsx
  fe/src/components/NavLinks/NavLinks.tsx
  fe/src/index.css
  fe/tailwind.config.js
Labels: 🛠 Fix, 🎨 UI, 🏗️ Refactor

#44 design #4: svg를 react 컴포넌트로 사용하기
  fe/src/assets/milestone.svg
  fe/src/assets/openedIssue.svg
  fe/src/assets/search.svg
  fe/src/common/Label/index.tsx
  fe/src/components/FilterBar/FilterBar.tsx
  fe/src/components/IssueList/Issue.tsx
  fe/src/components/IssueList/IssueList.tsx
  fe/src/components/NavLinks/NavLinks.tsx
  fe/src/pages/MainPage.tsx
Labels: 🧑🏻‍💻 FE, 🎨 UI

#50 chore #46: mock API를 위한 msw 설치 및 설정
  fe/package-lock.json
  fe/package.json
  fe/public/mockServiceWorker.js
  fe/src/App.tsx
  fe/src/common/Button/Button.stories.ts
  fe/src/common/Button/index.tsx
  fe/src/components/IssueList/Issue.tsx
  fe/src/components/IssueList/IssueList.tsx
  fe/src/components/NavLinks/NavLinks.tsx
  fe/src/index.tsx
  fe/src/mocks/browser.ts
  fe/src/mocks/handlers.ts
  fe/src/mocks/mainData.ts
  fe/src/pages/MainPage.tsx
Labels: 🧑🏻‍💻 FE, 🚀 Feat

#52 feat #51: 메인페이지 필터 기능 구현(ing)
  fe/src/components/FilterBar/FilterBar.tsx
  fe/src/components/FilterList/FilterList.stories.ts
  fe/src/components/FilterList/FilterList.tsx
  fe/src/components/IssueList/IssueList.tsx
  fe/src/pages/MainPage.tsx
Labels: 🧑🏻‍💻 FE, 🚀 Feat

#53 refactor #4: 버튼 컴포넌트 수정 및 적용
  fe/src/common/Button/index.tsx
  fe/src/components/FilterBar/FilterBar.tsx
  fe/src/components/IssueList/IssueList.tsx
  fe/src/components/NavLinks/NavLinks.tsx
Labels: 🧑🏻‍💻 FE, 🎨 UI, 🏗️ Refactor

#54 feat #51: 메인페이지 필터 기능
  fe/src/pages/MainPage.tsx
Labels: 🧑🏻‍💻 FE, 🚀 Feat

#55 feat #51: 드롭다운 기능 구현
  fe/src/common/Button/index.tsx
  fe/src/components/FilterList/FilterList.tsx
  fe/src/components/IssueList/IssueList.tsx
  fe/src/pages/MainPage.tsx
Labels: 🧑🏻‍💻 FE, 🚀 Feat

#56 refactor #51: 필터 버튼 배치 수정
  fe/src/common/Button/index.tsx
  fe/src/components/IssueList/IssueList.tsx
  fe/src/pages/MainPage.tsx
Labels: 🧑🏻‍💻 FE, 🎨 UI, 🏗️ Refactor

#59 feat #51: 이슈 상태에 따른 이슈 리스트 필터링 기능 구현
  fe/src/components/FilterList/FilterList.tsx
  fe/src/components/IssueList/Issue.stories.ts
  fe/src/components/IssueList/Issue.tsx
  fe/src/components/IssueList/IssueList.stories.ts
  fe/src/components/IssueList/IssueList.tsx
  fe/src/mocks/handlers.ts
  fe/src/mocks/mainData.ts
  fe/src/pages/MainPage.tsx
Labels: 🧑🏻‍💻 FE, 🚀 Feat

#60 feat #51: 메인페이지 서버 ip 연동
  fe/src/components/FilterList/FilterList.tsx
  fe/src/components/IssueList/Issue.stories.ts
  fe/src/components/IssueList/Issue.tsx
  fe/src/components/IssueList/IssueList.stories.ts
  fe/src/components/IssueList/IssueList.tsx
  fe/src/index.tsx
  fe/src/mocks/mainData.ts
  fe/src/mocks/temp.ts
  fe/src/pages/MainPage.tsx
Labels: 🧑🏻‍💻 FE, 🚀 Feat, 🏗️ Refactor

#62 design #4: 버튼 컴포넌트 폰트 사이즈 옵션 추가
  fe/src/common/Button/index.tsx
  fe/src/components/IssueList/Issue.tsx
  fe/src/pages/MainPage.tsx
Labels: 🧑🏻‍💻 FE, 🚀 Feat, 🛠 Fix

#78 feat #51: 메인 페이지 필터링 기능 구현(작성자, 레이블, 마일스톤) 외 기타 리펙토링
  fe/src/common/FilterItem/FilterItem.stories.ts
  fe/src/common/FilterItem/FilterItem.tsx
  fe/src/components/FilterList/FilterList.stories.ts
  fe/src/components/FilterList/FilterList.tsx
  fe/src/components/IssueTable/Issue.stories.ts
  fe/src/components/IssueTable/Issue.tsx
  fe/src/components/IssueTable/IssueTable.stories.ts
  fe/src/components/IssueTable/IssueTable.tsx
  fe/src/constants/Mainpage.ts
  fe/src/pages/MainPage.tsx
  fe/src/utils/getTimeElapsed.ts
  fe/tsconfig.json
  fe/tsconfig.paths.json
Labels: 🧑🏻‍💻 FE, 🚀 Feat, 🏗️ Refactor

#88 refactor #86: IssueListService의 IssueDto 로직 refactor
  be/src/main/java/com/issuetracker/domain/IssueListPage.java
  be/src/main/java/com/issuetracker/repository/IssueListRepository.java
  be/src/main/java/com/issuetracker/repository/IssueRepository.java
  be/src/main/java/com/issuetracker/service/IssueListService.java
Labels: 🧑🏻‍💻 BE, 🏗️ Refactor

#90 feat #16: Issue 등록 기능 구현
  be/src/main/java/com/issuetracker/controller/IssueController.java
  be/src/main/java/com/issuetracker/controller/MilestoneController.java
  be/src/main/java/com/issuetracker/domain/Assignee.java
  be/src/main/java/com/issuetracker/domain/Issue.java
  be/src/main/java/com/issuetracker/domain/IssueLabel.java
  be/src/main/java/com/issuetracker/domain/IssueListPage.java
  be/src/main/java/com/issuetracker/dto/issue/AssigneeDto.java
  be/src/main/java/com/issuetracker/dto/issue/IssuePostDto.java
  be/src/main/java/com/issuetracker/dto/issue/UserDto.java
  be/src/main/java/com/issuetracker/dto/label/LabelDto.java
  be/src/main/java/com/issuetracker/mapper/JacksonLocalDateTimeConfig.java
  be/src/main/java/com/issuetracker/repository/AssigneeRepository.java
  be/src/main/java/com/issuetracker/repository/IssueLabelRepository.java
  be/src/main/java/com/issuetracker/repository/IssueRepository.java
  be/src/main/java/com/issuetracker/service/IssueListService.java
  be/src/main/java/com/issuetracker/service/IssueService.java
  be/src/main/java/com/issuetracker/service/MilestoneService.java
Labels: 🧑🏻‍💻 BE, 🚀 Feat

#97 feat #19: 이슈 열기/닫기 기능 구현
  be/src/main/java/com/issuetracker/controller/IssueController.java
  be/src/main/java/com/issuetracker/dto/issue/IssueStatusDto.java
  be/src/main/java/com/issuetracker/dto/issueList/IssueListDto.java
  be/src/main/java/com/issuetracker/dto/issueList/IssueStatusListDto.java
  be/src/main/java/com/issuetracker/repository/IssueRepository.java
  be/src/main/java/com/issuetracker/service/IssueService.java
Labels: 🧑🏻‍💻 BE, 🚀 Feat

#98 댓글 추가, 수정 기능 구현
  be/src/main/java/com/issuetracker/controller/CommentController.java
  be/src/main/java/com/issuetracker/controller/IssueController.java
  be/src/main/java/com/issuetracker/domain/Comment.java
  be/src/main/java/com/issuetracker/dto/comment/CommentPostDto.java
  be/src/main/java/com/issuetracker/repository/CommentRepository.java
  be/src/main/java/com/issuetracker/service/CommentService.java
Labels: 🧑🏻‍💻 BE, 🚀 Feat

#104 feat #93: 댓글 삭제 기능 구현(예외처리 미완성)
  be/src/main/java/com/issuetracker/controller/CommentController.java
  be/src/main/java/com/issuetracker/domain/Comment.java
  be/src/main/java/com/issuetracker/service/CommentService.java
Labels: 🧑🏻‍💻 BE, 🚀 Feat

#106 feat #105: CORS 설정
  be/src/main/java/com/issuetracker/configuration/CorsConfigurer.java
Labels: 🧑🏻‍💻 BE, 🚀 Feat

#107 feat #51: 메인 페이지 필터 기능
  fe/src/common/FilterItem/FilterItem.stories.ts
  fe/src/common/FilterItem/FilterItem.tsx
  fe/src/components/FilterList/FilterList.stories.ts
  fe/src/components/FilterList/FilterList.tsx
  fe/src/components/IssueTable/IssueTable.stories.ts
  fe/src/components/IssueTable/IssueTable.tsx
  fe/src/components/NavLinks/NavLinks.tsx
  fe/src/constants/Constants.ts
  fe/src/pages/MainPage.tsx
Labels: 🧑🏻‍💻 FE, 🚀 Feat

#110 feat #51: 메인 페이지 필터시 서치바 텍스트 변경
  fe/src/components/FilterBar/FilterBar.stories.ts
  fe/src/components/FilterBar/FilterBar.tsx
  fe/src/pages/MainPage.tsx
Labels: 🧑🏻‍💻 FE, 🚀 Feat

#119 [iOS] 이슈목록 필터 적용
  ios/IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  ios/IssueTracker/IssueTracker/Common/FilterListFactory.swift
  ios/IssueTracker/IssueTracker/DataSenderDelegate.swift
  ios/IssueTracker/IssueTracker/IssueTab/Filter/FilterApplyList.swift
  ios/IssueTracker/IssueTracker/IssueTab/Filter/FilterListCollectionViewCell.swift
  ios/IssueTracker/IssueTracker/IssueTab/Filter/FilterListCollectionViewCell.xib
  ios/IssueTracker/IssueTracker/IssueTab/Filter/FilterListType.swift
  ios/IssueTracker/IssueTracker/IssueTab/Filter/FilterListUseCase.swift
  ios/IssueTracker/IssueTracker/IssueTab/Filter/FilterListViewController.swift
  ios/IssueTracker/IssueTracker/IssueTab/List/IssueListViewController.swift
  ios/IssueTracker/IssueTracker/Model/IssueFilterList.swift
  ios/IssueTracker/IssueTracker/Model/IssueList.swift
  ios/IssueTracker/IssueTracker/Network/DTO/IssueListDTO.swift
  ios/IssueTracker/IssueTracker/Network/NetworkManager.swift
Labels: 🧑🏻‍💻 iOS, 🚀 Feat, 🎨 UI

#113 [BE] 2주차 코드리뷰 피드백 반영
  be/build.gradle
  be/src/main/java/com/issuetracker/configuration/CorsConfigurer.java
  be/src/main/java/com/issuetracker/controller/IssueController.java
  be/src/main/java/com/issuetracker/controller/IssueListController.java
  be/src/main/java/com/issuetracker/controller/LabelController.java
  be/src/main/java/com/issuetracker/domain/Assignee.java
  be/src/main/java/com/issuetracker/domain/Comment.java
  be/src/main/java/com/issuetracker/domain/Issue.java
  be/src/main/java/com/issuetracker/domain/IssueLabel.java
  be/src/main/java/com/issuetracker/domain/Label.java
  be/src/main/java/com/issuetracker/domain/Milestone.java
  be/src/main/java/com/issuetracker/domain/User.java
  be/src/main/java/com/issuetracker/dto/comment/CommentPostDto.java
  be/src/main/java/com/issuetracker/dto/issue/AssigneeDto.java
  be/src/main/java/com/issuetracker/dto/issue/IssueCommentDto.java
  be/src/main/java/com/issuetracker/dto/issue/IssueDetailPageDto.java
  be/src/main/java/com/issuetracker/dto/issue/IssueLabelDto.java
  be/src/main/java/com/issuetracker/dto/issue/IssueMilestone.java
  be/src/main/java/com/issuetracker/dto/issue/UserDto.java
  be/src/main/java/com/issuetracker/dto/issueList/IssueListDto.java
  be/src/main/java/com/issuetracker/dto/milestone/MilestoneDto.java
  be/src/main/java/com/issuetracker/mapper/FilterListMapper.java
  be/src/main/java/com/issuetracker/mapper/IssueIdListMapper.java
  be/src/main/java/com/issuetracker/mapper/IssueListMapper.java
  be/src/main/java/com/issuetracker/mapper/JacksonLocalDateTimeConfig.java
  be/src/main/java/com/issuetracker/mapper/LabelToDtoMapper.java
  be/src/main/java/com/issuetracker/repository/CommentRepository.java
  be/src/main/java/com/issuetracker/repository/IssueListRepository.java
  be/src/main/java/com/issuetracker/repository/IssueRepository.java
  be/src/main/java/com/issuetracker/repository/LabelRepository.java
  be/src/main/java/com/issuetracker/repository/MilestoneRepository.java
  be/src/main/java/com/issuetracker/repository/UserRepository.java
  be/src/main/java/com/issuetracker/service/CommentService.java
  be/src/main/java/com/issuetracker/service/IssueListService.java
  be/src/main/java/com/issuetracker/service/IssueService.java
  be/src/main/java/com/issuetracker/service/LabelService.java
  be/src/main/java/com/issuetracker/service/MilestoneService.java
  be/src/main/resources/com/issuetracker/mapper/IssueIdListMapper.xml
  be/src/main/resources/com/issuetracker/mapper/IssueListMapper.xml
Labels: 🧑🏻‍💻 BE, 🏗️ Refactor

#122 [FE] feat: 메인페이지 체크 박스 기능 구현
  fe/src/common/FilterItem/FilterItem.tsx
  fe/src/components/FilterBar/FilterBar.stories.ts
  fe/src/components/FilterBar/FilterBar.tsx
  fe/src/components/FilterList/FilterList.tsx
  fe/src/components/FilterList/useOutsideClick.ts
  fe/src/components/IssueTable/Issue.stories.ts
  fe/src/components/IssueTable/Issue.tsx
  fe/src/components/IssueTable/IssueTable.tsx
  fe/src/constants/Constants.ts
  fe/src/pages/MainPage.tsx
  fe/tailwind.config.js
Labels: 🧑🏻‍💻 FE, 🚀 Feat

#132 [FE] feat #84: 이슈 상세 페이지 기능 구현 완료
  fe/src/components/IssueCommentInput/IssueCommentInput.tsx
  fe/src/components/IssueCommentItem/IssueCommentItem.tsx
  fe/src/components/IssueCommentList/IssueCommentList.tsx
  fe/src/components/IssueController/IssueController.tsx
  fe/src/components/IssueSubInfo/IssueSubInfo.tsx
  fe/src/pages/IssueDetailPage.tsx
  fe/src/utils/fetchSetData.ts
Labels: 🧑🏻‍💻 FE, 🚀 Feat

#136 [FE] feat #51: 이슈 필터 초기화
  fe/package.json
  fe/src/components/IssueTable/IssueTable.stories.ts
  fe/src/components/IssueTable/IssueTable.tsx
  fe/src/pages/MainPage.tsx
Labels: 🧑🏻‍💻 FE, 🚀 Feat

#143 [FE] feat #84: 코멘트 수정 시 ui 즉시 반영
  fe/src/components/IssueCommentItem/IssueCommentItem.tsx
  fe/src/components/IssueCommentList/IssueCommentList.tsx
  fe/src/pages/IssueDetailPage.tsx
Labels: 🧑🏻‍💻 FE, 🚀 Feat

#154 [FE] Feat: 로그인 페이지 구현
  fe/src/App.tsx
  fe/src/components/MilestoneTable/MilestoneItem.tsx
  fe/src/components/MilestoneTable/MilestoneTable.tsx
  fe/src/pages/LoginPage.tsx
  fe/src/pages/MilestonePage.tsx
Labels: 🧑🏻‍💻 FE, 🚀 Feat, 🎨 UI

#126 [FE] feat: 새로운 이슈 작성 UI
  fe/src/assets/checkOffCircle.svg
  fe/src/assets/checkOnCircle.svg
  fe/src/common/FilterItem/FilterItem.tsx
  fe/src/common/Label/index.tsx
  fe/src/common/Profile/index.tsx
  fe/src/components/FilterBar/FilterBar.tsx
  fe/src/components/FilterList/FilterList.tsx
  fe/src/components/IssueSubInfo/IssueSubInfo.tsx
  fe/src/components/IssueTable/IssueTable.tsx
  fe/src/components/NewIssue/NewIssue.stories.ts
  fe/src/components/NewIssue/NewIssue.tsx
  fe/src/components/NewIssue/NewIssueInput.stories.ts
  fe/src/components/NewIssue/NewIssueInput.tsx
  fe/src/components/NewIssue/NewIssueMain.stories.ts
  fe/src/components/NewIssue/NewIssueMain.tsx
  fe/src/components/NewIssue/NewIssueNav.stories.ts
  fe/src/components/NewIssue/NewIssueNav.tsx
  fe/src/components/NewIssue/NewIssueOptions.stories.ts
  fe/src/components/NewIssue/NewIssueOptions.tsx
Labels: 🧑🏻‍💻 FE, 🎨 UI
